import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import { Montserrat } from "next/font/google";
import { ThemeProvider } from "../components/Theme-provider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-Roboto",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "800", "900"],
  variable: "--font-montserrat",
});

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${montserrat.variable} !bg-white bg-no-repeat darK:bg-gradient-to-b dark:from-gray-900  dark:to-black duration-300`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}/
        </ThemeProvider>
      </body>
    </html>
  );
}
